import type Groq from "groq-sdk";

// No artificial per-word delay here — the text is already fully generated by
// the time this runs (came from a non-streaming completion), so any delay is
// pure added wall-clock time on top of real generation latency, and the
// serverless function stays alive until this stream closes.
export function textToStream(text: string): ReadableStream<Uint8Array> {
    const encoder = new TextEncoder();
    return new ReadableStream<Uint8Array>({
        start(controller) {
            controller.enqueue(encoder.encode(text));
            controller.close();
        },
    });
}

export function completionToStream(completion: AsyncIterable<Groq.Chat.Completions.ChatCompletionChunk>): ReadableStream<Uint8Array> {
    const encoder = new TextEncoder();
    return new ReadableStream<Uint8Array>({
        async start(controller) {
            try {
                for await (const chunk of completion) {
                    const text = chunk.choices[0]?.delta?.content ?? "";
                    if (text) controller.enqueue(encoder.encode(text));
                }
            } catch (err) {
                console.error("Groq stream error:", err);
            } finally {
                controller.close();
            }
        },
    });
}
